name: chip_companion
description: Professional pet microchip validator with Bluetooth and NFC scanning capabilities
publish_to: 'none'
version: 2.0.6+8

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: ">=3.35.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  js: ^0.6.7
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  flutter_blue_plus: ^2.0.0
  nfc_manager: ^4.1.1
  in_app_purchase: ^3.1.13
  permission_handler: ^11.3.0
  device_info_plus: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  # Ensure assets directory available
  assets:
    - assets/fonts/inter/
    - assets/data/

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21
  # Use the finalized store icon as the source for the in-app launcher icon
  image_path_android: "final_release_google_play_store/app_icon_512x512.png"
  image_path_ios: "final_release_google_play_store/app_icon_512x512.png"
  # Adaptive icon settings (Android 8+)
  adaptive_icon_background: "#0B1220" # brand background
  adaptive_icon_foreground: "final_release_google_play_store/app_icon_512x512.png"
