name: Flutter CI

on:
  pull_request:
  push:
    branches: [ main, sel-docs-icons-20251010 ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.x"
          channel: 'stable'

      - name: Print Flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test --reporter expanded

      - name: Build web (sanity check)
        run: flutter build web --release

      - name: Build Android APK (sanity check)
        run: flutter build apk --release --no-shrink
