name: Flutter CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.4'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Analyze code
      run: flutter analyze
    
    - name: Run tests
      run: flutter test --reporter expanded
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Build App Bundle
      run: flutter build appbundle --release
    
    - name: Check for INTERNET permission
      run: |
        # Extract permissions from main manifest
        PERMS=$(grep -i 'permission.*INTERNET' android/app/src/main/AndroidManifest.xml || true)
        if [ ! -z "$PERMS" ]; then
          echo "❌ ERROR: INTERNET permission found in main manifest!"
          echo "$PERMS"
          exit 1
        fi
        echo "✅ OK: No INTERNET permission in main manifest"
    
    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-bundle
        path: build/app/outputs/bundle/release/app-release.aab
        retention-days: 7
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 7
